In [ ]:
# OpenCV is a real-time computer vision and machine learning software library, containing more 
# than 2500 CV and ML algorithms.

# These algorithms can be used to detect and recognize faces, identify objects, classify human actions
# in videos, track camera movements, track moving objects, extract 3D models of objects, produce 3D 
# point clouds from stereo cameras, etc.

In [ ]:
# OpenCV in Python uses Numpy. Numpy is a highly optimized library for numerical calculations and 
# provides powerful functionalities including arrays. All the OpenCV array structures are converted 
# to and from Numpy arrays.

# Let’s install OpenCV and proceed ahead with our code: 

In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
# Let’s import OpenCV.

In [3]:
import cv2
import numpy as np

In [4]:
# The library is named OpenCV but actually, it has to import the cv2 module.

# As we discussed earlier, OpenCV uses Numpy for its effectiveness. Now what that actually means is, Numpy has strong array 
# support. Numpy arrays have an interesting and wide range of methods.

#And why we are discussing this? Because Every image used with OpenCV is nothing but a 3-dimensional Numpy Array!

# This 3-dimensional Numpy array contains BGR values ranging from 0-255, where B stands for Blue, G for Green, R stands for Red. 
# This value shows the BGR pixel value in an image.

# Let’s import our image, i.e. make our program read the sample image.

In [5]:
img = cv2.imread("dog.PNG", -1)

In [6]:
# imread() takes 2 parameters: path for the image and way in which image has to be read -> its default value is cv2.IMREAD_COLOR 
# i.e. 1 and the other two options available are cv2.IMREAD_GRAYSCALE which reads the image in gray mode n 
# takes 0 as value and cv2.IMREAD_UNCHANGED reads as it is and takes the value as -1.


# Now, to display the output we have to fire command.

In [7]:
cv2.imshow('Image', img)
cv2.waitKey(0)      
cv2.destroyAllWindows()

In [8]:
# imshow() is used to show the read image and takes two parameters: 1. window-name and 2. image to be returned

# cv2.waitKey() specifies the total time duration of the display. If passed 0, it will showcase the output till any key is hit.

# It takes parameters as time in milliseconds. The function is very important as it avoids the Python kernel from crashing.

# cv2.destroyAllWindows() closes all the open windows.

In [9]:
# Now, let’s display in grayscale by changing the parametric value to 0 in imread()

img = cv2.imread("dog.PNG", 0)
cv2.imshow('Image', img)
cv2.waitKey(0)       
cv2.destroyAllWindows()

# By pressing any key on the keyboard, the window will automatically close.

In [10]:
# We can resize it.

img = cv2.resize(img, (300,300))

# Here, cv2.resize() provides the ability to convert the image to the desired shape. Now, instead of providing the width and 
# height of the image you can actually provide fx and fy to denote how many times you have to scale the original image.

In [11]:
img = cv2.resize(img, (0,0), fx=0.3, fy=0.3)

#fx and fy denotes x and y parameters for scalability.

In [12]:
# These images are NumPy arrays. So let’s print the image and let’s see the output:

print(img)
print(img.shape) #returns shape of numpy array

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   1  11]
 ...
 [ 78  68  49 ... 109  90 100]
 [ 65  79  72 ... 112  73  80]
 [ 61  64  66 ...  92  93  91]]
(90, 90)


In [13]:
# From the output, it is very clear that the array is a 2d array with 27×27 pixels. Why 2d not 3d? 

# Because the image has been read in grayscale, let’s make the compiler read the image unchanged and check for the shape.

In [14]:
img = cv2.imread('dog.PNG', -1)
img = cv2.resize(img, (0,0), fx=0.3, fy=0.3)
print(img)
print(img.shape)

[[[  0   2   2 255]
  [  0   2   0 255]
  [  0   2   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]

 [[  0   2   2 255]
  [  1   3   1 255]
  [  0   3   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]

 [[  0   2   2 255]
  [  0   3   1 255]
  [  1   3   1 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]

 ...

 [[  3  85  37 255]
  [  0  78  37 255]
  [ 16 111  66 255]
  ...
  [ 15 130  85 255]
  [  1  83  40 255]
  [  2 104  61 255]]

 [[  3  94  49 255]
  [  0  85  41 255]
  [  8 114  62 255]
  ...
  [ 16 133  87 255]
  [ 17 107  61 255]
  [  8 100  64 255]]

 [[  5  44  24 255]
  [  2  48  24 255]
  [  2  47  25 255]
  ...
  [ 25 127  84 255]
  [  0 107  60 255]
  [  7 109  75 255]]]
(118, 118, 4)


In [15]:
# Now you can see 3d array here with BGR values of each pixel.

# END